services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file: .env
    ports:
      - "8080:80"
      - "443:443"
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file: .env
    networks:
      - inception

  wordpress:
    # image: wordpress:fpm
    container_name: wordpress
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/wordpress # Mount WordPress files
    env_file: .env
    depends_on:
      - mariadb
    networks:
      - inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jsteenpu/data/wordpress'
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jsteenpu/data/mariadb'

networks:
  inception:
    driver: bridge
