services:
  wordpress:
    image: wordpress:fpm
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html # Mount WordPress files
    environment:
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=jsteenpu
      - MARIADB_PASSWORD=19
      - MARIADB_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - wordpress-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=jsteenpu
      - MYSQL_PASSWORD=19
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf  # Custom config
      - ./mariadb/init_mariadb.sh:/docker-entrypoint-initdb.d/init_mariadb.sh  # Init script
    networks:
      - wordpress-network

volumes:
  mariadb_data:

networks:
  wordpress-network:
    driver: bridge
