version: '3'
services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env
    expose:
      - "3306"
    restart: unless-stopped
    
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    networks: 
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jsteenpu/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/jsteenpu/data/mariadb'

networks:
  inception:
    driver: bridge

